version: 1

reviews:
  # 자동 리뷰 설정 (boolean ❌ → object ⭕)
  auto_review:
    enabled: true

  # Draft PR은 리뷰 제외
  skip_draft: true

  # 리뷰 코멘트 방식
  comment_style: inline
  include_summary: true

  # 리뷰 우선순위
  severity_focus:
    - blocker
    - major

  # 과도한 코멘트 방지
  limits:
    max_comments_per_file: 8
    max_total_comments: 40
    avoid_repeat_comments: true

  # 리뷰 대상 파일 범위
  paths:
    include:
      - "src/**"
      - "build.gradle"
      - "build.gradle.kts"
      - "settings.gradle"
      - "settings.gradle.kts"
    exclude:
      - "**/*.md"
      - "**/*.adoc"
      - "**/*.txt"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.gif"
      - "**/*.svg"
      - "**/*.lock"
      - "**/generated/**"
      - "**/build/**"
      - "**/out/**"
      - "**/.gradle/**"

  # 리뷰 집중 영역
  focus_areas:
    - correctness
    - security
    - reliability
    - performance
    - testing

  # 스타일 관련 소음 최소화
  noise_control:
    style_comments: low
    naming_comments: low
    formatting_comments: low

  # 테스트 관점 강화
  testing:
    suggest_missing_tests: true
    require_edge_case_tests: true

  # 리뷰 마무리 문구 (성장 루프)
  closing_note:
    enabled: true
    template: "다음 PR에서 더 좋아지기 위한 1가지 루프를 제안한다: {{one_actionable_loop}}"

# PR 요약 생성
summary:
  enabled: true

# 보안 관련 기본 가드
security:
  warn_on_sensitive_logging: true
  sensitive_keywords:
    - password
    - passwd
    - secret
    - token
    - authorization
    - cookie
    - accessKey
    - privateKey

# 출력 언어 설정
output:
  language: ko-KR
  tone: formal
